config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'

  get 'dashboards/index'
  get 'dashboards/show'

  resources :exercises
  resources :calorie_intakes
  resources :weights
  resources :steps

end

app/models/calorie_intake.rb
class CalorieIntake < ActiveRecord::Base

  def self.calorie_intake_current_day
    intake_today = self.where("created_at BETWEEN ? AND ?",
       Time.now.beginning_of_day, Time.now)
    intake_today.all.sum(:calorie_intake)
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :exercise_type

  def self.calories_burned_current_day
    burned_today = self.where("created_at BETWEEN ? AND ?",
       Time.now.beginning_of_day, Time.now)
    burned_today.all.sum(:calories_burned)
  end
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  has_many :exercises
end

app/models/step.rb
class Step < ActiveRecord::Base
  def self.total_steps_taken
    self.sum(:steps_taken)
  end
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  validates :date_created, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/calorie_intake_controller.rb
class CalorieIntakeController < ApplicationController
  #manually-created controller
  before_action :set_calorie_intake, only: [:show, :edit, :update, :destroy]

  def index
    @calorie_intake = CalorieIntake.all
  end

  def show
  end

  def new
    @calorie_intake = CalorieIntake.new
  end

  def edit
  end

  def create
    @calorie_intake = CalorieIntake.new(calorie_intake_params)

    if @calorie_intake.save
      redirect_to @calorie_intake, notice: 'Your calorie intake was successfully created!'
    else
      render :new
    end
  end

  def update
    if @calorie_intake.update(calorie_intake_params)
      redirect to @calorie_intake, notice: "your calorie intake was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @calorie_intake.destroy
    redirect_to calorie_intake_url, notice: "your calorie intake was successfully destroyed."
  end

  private
  def set_calorie_intake
    @calorie_intake = CalorieIntake.find(params[:id])
  end

  def calorie_intake_params
    params.require(:calorie_intake).permit(:calorie_intake)
  end

end

app/controllers/calorie_intakes_controller.rb
class CalorieIntakesController < ApplicationController
  #manually-created controller
  before_action :set_calorie_intake, only: [:show, :edit, :update, :destroy]

  def index
    @calorie_intake = CalorieIntake.all
  end

  def show
  end

  def new
    @calorie_intake = CalorieIntake.new
  end

  def edit
  end

  def create
    @calorie_intake = CalorieIntake.new(calorie_intake_params)

    if @calorie_intake.save
      redirect_to @calorie_intake, notice: 'Your calorie intake was successfully created!'
    else
      render :new
    end
  end

  def update
    if @calorie_intake.update(calorie_intake_params)
      redirect_to @calorie_intake, notice: "your calorie intake was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @calorie_intake.destroy
    redirect_to calorie_intake_url, notice: "your calorie intake was successfully destroyed."
  end

  private
  def set_calorie_intake
    @calorie_intake = CalorieIntake.find(params[:id])
  end

  def calorie_intake_params
    params.require(:calorie_intake).permit(:calorie_intake)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @all_steps_ever = Step.total_steps_taken
    @calories_eaten = CalorieIntake.calorie_intake_current_day
    @calories_burned = Exercise.calories_burned_current_day
  end

  def show
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = Exercise.all
  end

  def show

  end

  def new
    @exercise = Exercise.new
  end

  def edit
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to @exercise, notice: 'Exercise was successfully created.'
    else
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to @exercise, notice: 'Exercise was successfully created.'
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    redirect_to exercises_url, notice: 'Exercise was successfully destroyed.'
  end

  private

    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:exercise_type_id, :calories_burned, :exercise_performed)
    end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  def index
    @steps = Step.all
  end

  # GET /steps/1
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  def create
    @step = Step.new(step_params)

    if @step.save
      redirect_to @step, notice: 'Step was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /steps/1
  def update
    if @step.update(step_params)
      redirect_to @step, notice: 'Step was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /steps/1
  def destroy
    @step.destroy
    redirect_to steps_url, notice: 'Step was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def step_params
      params.require(:step).permit(:steps_taken)
    end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]
  #belongs_to :exercise_types
  # GET /weights
  def index
    @weights = Weight.all
  end

  # GET /weights/1
  def show
  end

  # GET /weights/new
  def new
    @weight = Weight.new
  end

  # GET /weights/1/edit
  def edit
  end

  def create
  #   @weight = Weight.where(created_at: Time.now.beginning_of_day.utc..Time.now.end_of_day.utc).first_or_create!
  #   redirect_to @weight
  # end
    #@weight.update_attributes(weight_params)
    @weight = Weight.new(weight_params)
    if @weight.save
      redirect_to @weight, notice: 'Success!'
    else
      render :new
    end
  end

  # POST /weights
  # def create
  #   @weight = Weight.new(weight_params)
  #
  #   if @weight.save
  #     redirect_to @weight, notice: 'Weight was successfully created.'
  #   else
  #     render :new
  #   end
  # end

  # PATCH/PUT /weights/1
  def update
    if @weight.update(weight_params)
      redirect_to @weight, notice: 'Weight was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /weights/1
  def destroy
    @weight.destroy
    redirect_to weights_url, notice: 'Weight was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def weight_params
      params.require(:weight).permit(:weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/calorie_intake_helper.rb
module CalorieIntakeHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
  
end

app/views/calorie_intake/new.html.erb
<h1>new calorie intake amount</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_index_path %>

app/views/calorie_intakes/edit.html.erb
<h1>editing calories consumed</h1>

<%= render 'form' %>

<p><%= link_to 'Show', @calorie_intake %> </p>
<p><%= link_to 'Back', dashboards_index_path %></p>
<%= link_to 'Dashboard', root_path %>

app/views/calorie_intakes/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>calories consumed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calorie_intake.each do |calorie_intake| %>
      <tr>
        <td><%= calorie_intake.calorie_intake %></td>
        <td><%= calorie_intake.created_at %></td>
        <td><%= link_to 'Show', calorie_intake_path(calorie_intake) %></td>
        <td><%= link_to 'Edit', edit_calorie_intake_path(calorie_intake) %></td>
        <td><%= link_to 'Destroy', calorie_intake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_calorie_intake_path %>
<%= link_to 'Dashboard', root_path %>

app/views/calorie_intakes/new.html.erb
<h1>new calorie intake amount</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/calorie_intakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>calories consumed:</strong>
  <%= @calorie_intake.calorie_intake %>
<p>

  <%= link_to 'Edit', edit_calorie_intake_path(@calorie_intake) %> |
  <%= link_to 'Back', dashboards_index_path %>
  <%= link_to 'Dashboard', root_path %>

app/views/dashboards/index.html.erb
<h1>Welcome to Hracker!</h1>
<h2>the health and fitness training app</h2>

<p>You have taken <%=@all_steps_ever%> steps over the life of this app!</p>

<p>You consumed <%= @calories_eaten %> calories today!</p>
<p>You burned <%= @calories_burned %> calories today!</p>
<p>Your calorie budget for today is <%= @calories_eaten - @calories_burned %> calories !</p>


<p><%= link_to 'New Step', new_step_path %></p>

<p><%= link_to 'New Weight', new_weight_path %></p>

<p><%= link_to 'New Calories Consumed', new_calorie_intake_path %></p>

<p><%= link_to 'New Exercise', new_exercise_path %></p>

app/views/dashboards/show.html.erb
<h1>Dashboards#show</h1>
<p>Find me in app/views/dashboards/show.html.erb</p>

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercise_performed %><br>
    <%= f.text_field :exercise_performed %>
  </div>
  <div class="field">
    <%= f.label :calories_burned %><br>
    <%= f.number_field :calories_burned %>
  </div>
  <div class="field">
    <%= f.label :exercise_type_id %><br>
    <%= f.collection_select :exercise_type_id, ExerciseType.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercises</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>
<%= link_to 'Dashboard', root_path %>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Exercise performed</th>
      <th>Calories burned</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.exercise_performed %></td>
        <td><%= exercise.calories_burned %></td>
        <td><%= exercise.created_at %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>
<%= link_to 'Dashboard', root_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>


<br/>
<%= link_to 'See all exercise entries', exercises_path %>
<br/>
<br/>
<%= link_to 'Back to dashboard', root_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exercise performed</strong>
  <%= @exercise.exercise_performed %>
<p>

<p>
  <strong>ID</strong>
  <%= @exercise.id %>
<p>

  <p>
    <strong>Calories burned</strong>
    <%= @exercise.calories_burned %>
  <p>

  <%= link_to 'Edit', exercises_path %> |
  <%= link_to 'Back', dashboards_index_path %>
  <%= link_to 'Dashboard', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :steps_taken %><br>
    <%= f.number_field :steps_taken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Steps Taken</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Steps</h1>

<table>
  <thead>
    <tr>
      <th>Steps taken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.steps_taken %></td>
        <td><%= step.created_at %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>
<%= link_to 'Dashboard', root_path %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render 'form' %>


<br/>
<%= link_to 'See all steps taken', steps_path %>
<br/>
<br/>
<%= link_to 'Back to dashboard', root_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Steps taken:</strong>
  <%= @step.steps_taken %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>
<%= link_to 'Dashboard', root_path %>

app/views/weights/_form.html.erb
<%= form_for(@weight) do |f| %>
  <% if @weight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @weight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weights/create.html.erb
<h1>New Weight</h1>

<%= render 'form' %>


<br/>
<%= link_to 'See all weight entries', weights_path %>
<br/>
<br/>
<%= link_to 'Back to dashboard', root_path %>

app/views/weights/edit.html.erb
<h1>Editing Weight</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight %> |
<%= link_to 'Back', weights_path %>
<%= link_to 'Dashboard', root_path %>

app/views/weights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weights</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weights.each do |weight| %>
      <tr>
        <td><%= weight.weight %></td>
        <td><%= weight.created_at %></td>
        <td><%= link_to 'Show', weight %></td>
        <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
        <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weight', new_weight_path %>
<%= link_to 'Dashboard', root_path %>

app/views/weights/new.html.erb
<h1>New Weight</h1>

<%= render 'form' %>


<br/>
<%= link_to 'See all weight entries', weights_path %>
<br/>
<br/>
<%= link_to 'Back to dashboard', root_path %>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight entry for <%= @weight.created_at.strftime("%b %d, %Y") %></strong>
  <br/>
  <br/>
  <%= @weight.weight %>
</p>

<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>
<%= link_to 'Dashboard', root_path %>